### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by Dakror** [malizhev/vite-plugin-css-auto-import#1]
Thanks for this cool plugin, it would definitely be a time saver.

However on Windows, the current import logic does not work. The logic to lookup the styles for the virtual id expects the URL to start with a / and then some path, but on Windows, those absolute paths start with a drive identifier, e.g. C:/<path>.

**Comment by malizhev** [comment]
@Dakror Hi. Sorry for the long reply. I've checked it on Windows. Didn't work, indeed.

**Comment by malizhev** [comment]
@Dakror I've made [a fix](https://github.com/malizhev/vite-plugin-css-auto-import/commit/02f01dc717da38a677948fa96d5ed3afdfe45ddd).
Please check the latest version (0.5.0) on npm. Could you let me know if you have other issues? Hope now you'll be able to start using it in your projects.
I'm closing this issue for now. Feel free to reopen if needed. Cheers 🍻

**Comment by malizhev** [comment]
@Dakror I've made [a fix](https://github.com/malizhev/vite-plugin-css-auto-import/commit/02f01dc717da38a677948fa96d5ed3afdfe45ddd).
Please check the latest version (0.5.0) on npm. Could you let me know if you have other issues? Hope now you'll be able to start using it in your projects.
I'm closing this issue for now. Feel free to reopen if needed. Cheers 🍻

**Comment by Dakror** [comment]
Thanks for the fix, this definitely helped. However now SASS compilation fails during the import of those auto-imported scss files.

It can't find the @import-ed stylesheets that are referenced in my stylesheets using relative paths. So something about the working directory for sass compilation inside this plugin must be wrong i guess.

Example error message:
```
10:58:03 [vite] Internal server error: [sass] Can't find stylesheet to import.
  ╷
1 │ @import "../style/variables.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  virtual:css-auto-import\98ec907e6be21\originalModuleId=<stylesheet>.scss 1:9  root stylesheet
```

EDIT: I can't seem to re-open the issue.
